name: unit test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  unit_test:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cd HTTPMock && swift test